Carrltz disable commands not verified
datasektionen/harmony pull request #80
Opened 2022-10-23 13:13 UTC by Carlltz

Inaktiverar kommando användande utöver "/verify" för alla som inte har "verified" rollen. 
Skapad till ett Issue av Niklas.

2022-10-24 14:45 UTC, niklasvatn requested changes
Thanks, Carl! Looks good.
But, please fix the comment about the `if`. Then I can approve.

2022-10-24 14:45 UTC, niklasvatn commented on src/commands/handle-commands.ts
> +			if (guild && (await hasRoleVerified(user, guild))) {
Do a guard before the if.

```
if (!guild) {
 throw
}
if (await hasRole...) {...}
else {...}
```

2022-10-24 14:45 UTC, niklasvatn commented on src/commands/handle-commands.ts
> +				throw new Error("Couldn't get guild from interaction!");
Remove with the changes suggested.
In general, do not nest if/else if it can be avoided. It is difficult to read and to understand what is checked.

2022-10-24 14:45 UTC, niklasvatn commented on src/commands/handle-commands.ts
> +							"Permission denied!\nYou first need to verify yourself using the \"/verify begin\" command.",
Alternatively, you can use `\`format strings \``
Then you don't have to write \n, but can make line breaks. The sad thing is that they are tab-preserving as well so you will have to create a nice util  to remove those (it is a quite easy regex) or format the code very ugly :)

2022-10-24 14:46 UTC, niklasvatn commented on src/commands/handle-commands.ts
> +							"Permission denied!\nYou first need to verify yourself using the \"/verify begin\" command.",
@Hampfh it is a bit weird that he got a lint error using single quotes when string contains double quotes. I think prettier should allow this. Do you know anything here?

2022-10-24 19:01 UTC, Carlltz commented on src/commands/handle-commands.ts
> +							"Permission denied!\nYou first need to verify yourself using the \"/verify begin\" command.",
Agreed singeticks look maybe a little bit better! Fixed.

2022-10-24 19:10 UTC, Carlltz commented
Thanks for the constructive feedback Niklas! I've now updated the file accordingly.
Just tell me if there's something more to change!

2022-10-24 19:14 UTC, niklasvatn commented
Realized that we can improve some other code based on this check. Will write some tomorrow.

2022-10-24 19:40 UTC, Hampfh commented on src/commands/handle-commands.ts
> +							"Permission denied!\nYou first need to verify yourself using the \"/verify begin\" command.",
Did you guys solve this? I don't recognize that prettier problem

2022-10-25 17:46 UTC, niklasvatn commented
> Realized that we can improve some other code based on this check. Will write some suggestions tomorrow.

As promised.
So we do only want interaction with the bot to be allowed in Guilds. Doing this check that you make initially here makes a lot of sense. But we do currently not make use of this in our handlers. They are defined to take `ChatInputCommandInteraction` as an argument. That type has the property `guild?: Guild`, but we can now use a type where Guild is not undefined. I highly doubt that this _augmented_ type is natively available in the library. But we could instead define a new type 

```ts
type GuildChatInputCommandInteraction = Omit<ChatInputCommandInteraction, 'guild'> & {
   guild: Guild
}
````

and use this to type our functions. I think you have to use Omit here to override the property (@Hampfh do you know if there is a prettier way of doing this?). Also, you can probably come up with a more concise name if you want to. Once this is done, then we can remove the check `if(!interaction.guild) {...}` from other files!

2022-10-25 17:54 UTC, Hampfh commented
> ```ts
> type GuildChatInputCommandInteraction = Omit<ChatInputCommandInteraction, 'guild'> & {
>    guild: Guild
> }
> ```

I think this is the best way of doing it unless guild is the only optional field in the object, if that's the case we could use `Required<ChatInputCommandInteraction>`

2022-10-26 06:51 UTC, niklasvatn commented
> 

We can't mark every field required. We only want to override Guild right now I think.

2022-10-29 07:54 UTC, niklasvatn approved these changes
Let's do the typing stuff in a later PR.

2022-10-29 13:32 UTC, niklasvatn approved these changes
Nice !

2022-10-29 13:33 UTC, merged